#!/bin/sh

# script/server: Launch the application and any extra required processes
# locally.

set -e

cd "$(dirname "$0")/.."

test -z "$HANAMI_ENV" && HANAMI_ENV='development'

# Boot the app and any other necessary processes
OVERMIND_PORT=3000 overmind start -f Procfile.dev
