#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
# back to the initial first unused state.

set -e

if [ "$1" == "docker" ]; then
  script/bootstrap docker
  docker compose up
else
  cd "$(dirname "$0")/.."

  script/bootstrap

  echo "==> Copying config files"
  if [ ! -f ".env" ]; then
    cp .env-example .env
  fi

  echo "==> Setting up database..."
  bin/run db setup

  echo "==> App is now ready to go!"
fi
